version: '2'
services:
    jgallery-app:
        image: jgallery
        external_links:
            - jgallery-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=JGallery
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jgallery-mongodb:
        extends:
            file: mongodb.yml
            service: jgallery-mongodb
